### ISSUE TITLE
Some issues with negative exponential numbers (scientific e notation)

### ISSUE THREAD

**Issue by scorpion9979** [paulrberg/evm-fp#3]
I noticed that when representing very small numbers like 10 * 10<sup>-18</sup> (10 with 0 decimals), the following line works: `fp("1e-17")`, while the following line doesn't `fp("10e-18")`. Apparently, `fp("10e-18")` is internally interpreted to be equal to 1 * 10<sup>-18</sup>, so does `fp("100e-19")` and `fp("1000e-20")`.

**Comment by scorpion9979** [comment]
Update: Also noticed that `fp("18e-18")` causes the error:
`{`
`  reason: 'cannot raise to negative values',`
`  code: 'NUMERIC_FAULT',`
`  fault: 'cannot raise to negative values',`
`  operation: 'pow'`
`}`

While `fp("1.8e-17")` and `fp("0.18e-16")` work just fine.

**Comment by paulrberg** [comment]
Good catch. The cause for this may be this bit of code:

https://github.com/paulrberg/evm-fp/blob/f7f4d0451a26482974bdeae04f73ef28a32df4ce/src/index.ts#L21-L25

**Comment by scorpion9979** [comment]
> Good catch. The cause for this may be this bit of code:
> 
> https://github.com/paulrberg/evm-fp/blob/f7f4d0451a26482974bdeae04f73ef28a32df4ce/src/index.ts#L21-L25

Apparently the bug is in [from-exponential](https://github.com/shrpne/from-exponential).

![image](https://user-images.githubusercontent.com/4002635/119412890-48d72200-bcf5-11eb-853c-53f75d07d250.png)

Already opened an issue here https://github.com/shrpne/from-exponential/issues/7.

**Comment by paulrberg** [comment]
I opened a [PR](https://github.com/shrpne/from-exponential/pull/8) to fix the from-exponential bug. Once the author merges it and ships the new version to npm, I will upgrade the dependency in this package and ship a new version of evm-fp.
