### ISSUE TITLE
Feature request: ability to change decimals from it's default value (18)

### ISSUE THREAD

**Issue by scorpion9979** [paulrberg/evm-fp#5]
It would make it easier to represent values in certain contexts. E.g., `fp("1", 8)` for the following example.
In this feature, 18 would be the default number of decimals (e.g., `fp("1")` is the same as `fp("1", 18)`).

![image](https://user-images.githubusercontent.com/4002635/119367939-22949080-bcbb-11eb-95db-560c88224bad.png)

**Comment by paulrberg** [comment]
Thanks! But I'll close this since it's a duplicate of #2.
